/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorWalletRouteImport } from './routes/vendor.wallet'
import { Route as VendorStatusRouteImport } from './routes/vendor.status'
import { Route as VendorSocialRouteImport } from './routes/vendor.social'
import { Route as VendorShopRouteImport } from './routes/vendor.shop'
import { Route as VendorServicesRouteImport } from './routes/vendor.services'
import { Route as VendorRegisterRouteImport } from './routes/vendor.register'
import { Route as VendorKycRouteImport } from './routes/vendor.kyc'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as VendorChatRouteImport } from './routes/vendor.chat'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CCodeRouteImport } from './routes/c.$code'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminSystemStatusRouteImport } from './routes/admin.system-status'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSmsRouteImport } from './routes/admin.sms'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMapsRouteImport } from './routes/admin.maps'
import { Route as AdminLogisticsRouteImport } from './routes/admin.logistics'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLegalRouteImport } from './routes/admin.legal'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminFirebaseRouteImport } from './routes/admin.firebase'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCoinsRouteImport } from './routes/admin.coins'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminCashfreeRouteImport } from './routes/admin.cashfree'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as VendorLeadIdRouteImport } from './routes/vendor.lead.$id'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorWalletRoute = VendorWalletRouteImport.update({
  id: '/vendor/wallet',
  path: '/vendor/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorStatusRoute = VendorStatusRouteImport.update({
  id: '/vendor/status',
  path: '/vendor/status',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSocialRoute = VendorSocialRouteImport.update({
  id: '/vendor/social',
  path: '/vendor/social',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorShopRoute = VendorShopRouteImport.update({
  id: '/vendor/shop',
  path: '/vendor/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorServicesRoute = VendorServicesRouteImport.update({
  id: '/vendor/services',
  path: '/vendor/services',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRegisterRoute = VendorRegisterRouteImport.update({
  id: '/vendor/register',
  path: '/vendor/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorKycRoute = VendorKycRouteImport.update({
  id: '/vendor/kyc',
  path: '/vendor/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorChatRoute = VendorChatRouteImport.update({
  id: '/vendor/chat',
  path: '/vendor/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CCodeRoute = CCodeRouteImport.update({
  id: '/c/$code',
  path: '/c/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemStatusRoute = AdminSystemStatusRouteImport.update({
  id: '/system-status',
  path: '/system-status',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmsRoute = AdminSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapsRoute = AdminMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticsRoute = AdminLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFirebaseRoute = AdminFirebaseRouteImport.update({
  id: '/firebase',
  path: '/firebase',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoinsRoute = AdminCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCashfreeRoute = AdminCashfreeRouteImport.update({
  id: '/cashfree',
  path: '/cashfree',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const VendorLeadIdRoute = VendorLeadIdRouteImport.update({
  id: '/vendor/lead/$id',
  path: '/vendor/lead/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/quick': typeof QuickRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/status': typeof StatusRoute
  '/vendors': typeof VendorsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/cashfree': typeof AdminCashfreeRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/firebase': typeof AdminFirebaseRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/system-status': typeof AdminSystemStatusRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/c/$code': typeof CCodeRoute
  '/product/$id': typeof ProductIdRoute
  '/r/$code': typeof RCodeRoute
  '/vendor/chat': typeof VendorChatRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/kyc': typeof VendorKycRoute
  '/vendor/register': typeof VendorRegisterRoute
  '/vendor/services': typeof VendorServicesRoute
  '/vendor/shop': typeof VendorShopRoute
  '/vendor/social': typeof VendorSocialRoute
  '/vendor/status': typeof VendorStatusRoute
  '/vendor/wallet': typeof VendorWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/lead/$id': typeof VendorLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/quick': typeof QuickRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/status': typeof StatusRoute
  '/vendors': typeof VendorsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/cashfree': typeof AdminCashfreeRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/firebase': typeof AdminFirebaseRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/system-status': typeof AdminSystemStatusRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/c/$code': typeof CCodeRoute
  '/product/$id': typeof ProductIdRoute
  '/r/$code': typeof RCodeRoute
  '/vendor/chat': typeof VendorChatRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/kyc': typeof VendorKycRoute
  '/vendor/register': typeof VendorRegisterRoute
  '/vendor/services': typeof VendorServicesRoute
  '/vendor/shop': typeof VendorShopRoute
  '/vendor/social': typeof VendorSocialRoute
  '/vendor/status': typeof VendorStatusRoute
  '/vendor/wallet': typeof VendorWalletRoute
  '/admin': typeof AdminIndexRoute
  '/vendor/lead/$id': typeof VendorLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/quick': typeof QuickRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/status': typeof StatusRoute
  '/vendors': typeof VendorsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/cashfree': typeof AdminCashfreeRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/firebase': typeof AdminFirebaseRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/system-status': typeof AdminSystemStatusRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/c/$code': typeof CCodeRoute
  '/product/$id': typeof ProductIdRoute
  '/r/$code': typeof RCodeRoute
  '/vendor/chat': typeof VendorChatRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/kyc': typeof VendorKycRoute
  '/vendor/register': typeof VendorRegisterRoute
  '/vendor/services': typeof VendorServicesRoute
  '/vendor/shop': typeof VendorShopRoute
  '/vendor/social': typeof VendorSocialRoute
  '/vendor/status': typeof VendorStatusRoute
  '/vendor/wallet': typeof VendorWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/lead/$id': typeof VendorLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/home'
    | '/orders'
    | '/profile'
    | '/quick'
    | '/referral'
    | '/register'
    | '/services'
    | '/status'
    | '/vendors'
    | '/admin/branding'
    | '/admin/cashfree'
    | '/admin/catalog'
    | '/admin/coins'
    | '/admin/customers'
    | '/admin/firebase'
    | '/admin/forms'
    | '/admin/kyc'
    | '/admin/legal'
    | '/admin/login'
    | '/admin/logistics'
    | '/admin/maps'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/referrals'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/staff'
    | '/admin/system-status'
    | '/admin/vendors'
    | '/admin/whatsapp'
    | '/c/$code'
    | '/product/$id'
    | '/r/$code'
    | '/vendor/chat'
    | '/vendor/dashboard'
    | '/vendor/kyc'
    | '/vendor/register'
    | '/vendor/services'
    | '/vendor/shop'
    | '/vendor/social'
    | '/vendor/status'
    | '/vendor/wallet'
    | '/admin/'
    | '/vendor/lead/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/home'
    | '/orders'
    | '/profile'
    | '/quick'
    | '/referral'
    | '/register'
    | '/services'
    | '/status'
    | '/vendors'
    | '/admin/branding'
    | '/admin/cashfree'
    | '/admin/catalog'
    | '/admin/coins'
    | '/admin/customers'
    | '/admin/firebase'
    | '/admin/forms'
    | '/admin/kyc'
    | '/admin/legal'
    | '/admin/login'
    | '/admin/logistics'
    | '/admin/maps'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/referrals'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/staff'
    | '/admin/system-status'
    | '/admin/vendors'
    | '/admin/whatsapp'
    | '/c/$code'
    | '/product/$id'
    | '/r/$code'
    | '/vendor/chat'
    | '/vendor/dashboard'
    | '/vendor/kyc'
    | '/vendor/register'
    | '/vendor/services'
    | '/vendor/shop'
    | '/vendor/social'
    | '/vendor/status'
    | '/vendor/wallet'
    | '/admin'
    | '/vendor/lead/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/home'
    | '/orders'
    | '/profile'
    | '/quick'
    | '/referral'
    | '/register'
    | '/services'
    | '/status'
    | '/vendors'
    | '/admin/branding'
    | '/admin/cashfree'
    | '/admin/catalog'
    | '/admin/coins'
    | '/admin/customers'
    | '/admin/firebase'
    | '/admin/forms'
    | '/admin/kyc'
    | '/admin/legal'
    | '/admin/login'
    | '/admin/logistics'
    | '/admin/maps'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/referrals'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/staff'
    | '/admin/system-status'
    | '/admin/vendors'
    | '/admin/whatsapp'
    | '/c/$code'
    | '/product/$id'
    | '/r/$code'
    | '/vendor/chat'
    | '/vendor/dashboard'
    | '/vendor/kyc'
    | '/vendor/register'
    | '/vendor/services'
    | '/vendor/shop'
    | '/vendor/social'
    | '/vendor/status'
    | '/vendor/wallet'
    | '/admin/'
    | '/vendor/lead/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  HomeRoute: typeof HomeRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  QuickRoute: typeof QuickRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  StatusRoute: typeof StatusRoute
  VendorsRoute: typeof VendorsRoute
  CCodeRoute: typeof CCodeRoute
  ProductIdRoute: typeof ProductIdRoute
  RCodeRoute: typeof RCodeRoute
  VendorChatRoute: typeof VendorChatRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorKycRoute: typeof VendorKycRoute
  VendorRegisterRoute: typeof VendorRegisterRoute
  VendorServicesRoute: typeof VendorServicesRoute
  VendorShopRoute: typeof VendorShopRoute
  VendorSocialRoute: typeof VendorSocialRoute
  VendorStatusRoute: typeof VendorStatusRoute
  VendorWalletRoute: typeof VendorWalletRoute
  VendorLeadIdRoute: typeof VendorLeadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/wallet': {
      id: '/vendor/wallet'
      path: '/vendor/wallet'
      fullPath: '/vendor/wallet'
      preLoaderRoute: typeof VendorWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/status': {
      id: '/vendor/status'
      path: '/vendor/status'
      fullPath: '/vendor/status'
      preLoaderRoute: typeof VendorStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/social': {
      id: '/vendor/social'
      path: '/vendor/social'
      fullPath: '/vendor/social'
      preLoaderRoute: typeof VendorSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/shop': {
      id: '/vendor/shop'
      path: '/vendor/shop'
      fullPath: '/vendor/shop'
      preLoaderRoute: typeof VendorShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/services': {
      id: '/vendor/services'
      path: '/vendor/services'
      fullPath: '/vendor/services'
      preLoaderRoute: typeof VendorServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/register': {
      id: '/vendor/register'
      path: '/vendor/register'
      fullPath: '/vendor/register'
      preLoaderRoute: typeof VendorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/kyc': {
      id: '/vendor/kyc'
      path: '/vendor/kyc'
      fullPath: '/vendor/kyc'
      preLoaderRoute: typeof VendorKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/chat': {
      id: '/vendor/chat'
      path: '/vendor/chat'
      fullPath: '/vendor/chat'
      preLoaderRoute: typeof VendorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$code': {
      id: '/c/$code'
      path: '/c/$code'
      fullPath: '/c/$code'
      preLoaderRoute: typeof CCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-status': {
      id: '/admin/system-status'
      path: '/system-status'
      fullPath: '/admin/system-status'
      preLoaderRoute: typeof AdminSystemStatusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sms': {
      id: '/admin/sms'
      path: '/sms'
      fullPath: '/admin/sms'
      preLoaderRoute: typeof AdminSmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maps': {
      id: '/admin/maps'
      path: '/maps'
      fullPath: '/admin/maps'
      preLoaderRoute: typeof AdminMapsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistics': {
      id: '/admin/logistics'
      path: '/logistics'
      fullPath: '/admin/logistics'
      preLoaderRoute: typeof AdminLogisticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/firebase': {
      id: '/admin/firebase'
      path: '/firebase'
      fullPath: '/admin/firebase'
      preLoaderRoute: typeof AdminFirebaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coins': {
      id: '/admin/coins'
      path: '/coins'
      fullPath: '/admin/coins'
      preLoaderRoute: typeof AdminCoinsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cashfree': {
      id: '/admin/cashfree'
      path: '/cashfree'
      fullPath: '/admin/cashfree'
      preLoaderRoute: typeof AdminCashfreeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/lead/$id': {
      id: '/vendor/lead/$id'
      path: '/vendor/lead/$id'
      fullPath: '/vendor/lead/$id'
      preLoaderRoute: typeof VendorLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminCashfreeRoute: typeof AdminCashfreeRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCoinsRoute: typeof AdminCoinsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFirebaseRoute: typeof AdminFirebaseRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogisticsRoute: typeof AdminLogisticsRoute
  AdminMapsRoute: typeof AdminMapsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSmsRoute: typeof AdminSmsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminSystemStatusRoute: typeof AdminSystemStatusRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrandingRoute: AdminBrandingRoute,
  AdminCashfreeRoute: AdminCashfreeRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCoinsRoute: AdminCoinsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFirebaseRoute: AdminFirebaseRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminKycRoute: AdminKycRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogisticsRoute: AdminLogisticsRoute,
  AdminMapsRoute: AdminMapsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSmsRoute: AdminSmsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminSystemStatusRoute: AdminSystemStatusRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  HomeRoute: HomeRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  QuickRoute: QuickRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  StatusRoute: StatusRoute,
  VendorsRoute: VendorsRoute,
  CCodeRoute: CCodeRoute,
  ProductIdRoute: ProductIdRoute,
  RCodeRoute: RCodeRoute,
  VendorChatRoute: VendorChatRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorKycRoute: VendorKycRoute,
  VendorRegisterRoute: VendorRegisterRoute,
  VendorServicesRoute: VendorServicesRoute,
  VendorShopRoute: VendorShopRoute,
  VendorSocialRoute: VendorSocialRoute,
  VendorStatusRoute: VendorStatusRoute,
  VendorWalletRoute: VendorWalletRoute,
  VendorLeadIdRoute: VendorLeadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
