/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForVendorsRouteImport } from './routes/for-vendors'
import { Route as ForCustomersRouteImport } from './routes/for-customers'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorWalletRouteImport } from './routes/vendor.wallet'
import { Route as VendorStatusRouteImport } from './routes/vendor.status'
import { Route as VendorSocialRouteImport } from './routes/vendor.social'
import { Route as VendorShopRouteImport } from './routes/vendor.shop'
import { Route as VendorServicesRouteImport } from './routes/vendor.services'
import { Route as VendorRegisterRouteImport } from './routes/vendor.register'
import { Route as VendorKycRouteImport } from './routes/vendor.kyc'
import { Route as VendorInstallRouteImport } from './routes/vendor.install'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as VendorChatRouteImport } from './routes/vendor.chat'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as CCodeRouteImport } from './routes/c.$code'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminTestAccountsRouteImport } from './routes/admin.test-accounts'
import { Route as AdminSystemStatusRouteImport } from './routes/admin.system-status'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSmsRouteImport } from './routes/admin.sms'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMapsRouteImport } from './routes/admin.maps'
import { Route as AdminLookupRouteImport } from './routes/admin.lookup'
import { Route as AdminLogisticsRouteImport } from './routes/admin.logistics'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLegalRouteImport } from './routes/admin.legal'
import { Route as AdminKycReviewRouteImport } from './routes/admin.kyc-review'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminFirebaseRouteImport } from './routes/admin.firebase'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminDevicesRouteImport } from './routes/admin.devices'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCoinsRouteImport } from './routes/admin.coins'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminCashfreeRouteImport } from './routes/admin.cashfree'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminWebIndexRouteImport } from './routes/admin.web.index'
import { Route as VendorLeadIdRouteImport } from './routes/vendor.lead.$id'
import { Route as ApiPublicVendorLocationRouteImport } from './routes/api.public.vendor-location'
import { Route as AdminWebTestimonialsRouteImport } from './routes/admin.web.testimonials'
import { Route as AdminWebSeoRouteImport } from './routes/admin.web.seo'
import { Route as AdminWebSectionsRouteImport } from './routes/admin.web.sections'
import { Route as AdminWebPricingRouteImport } from './routes/admin.web.pricing'
import { Route as AdminWebOffersRouteImport } from './routes/admin.web.offers'
import { Route as AdminWebMediaRouteImport } from './routes/admin.web.media'
import { Route as AdminWebHeroRouteImport } from './routes/admin.web.hero'
import { Route as AdminWebFormsRouteImport } from './routes/admin.web.forms'
import { Route as AdminWebFaqsRouteImport } from './routes/admin.web.faqs'
import { Route as AdminWebDevicesRouteImport } from './routes/admin.web.devices'
import { Route as AdminWebBlogRouteImport } from './routes/admin.web.blog'
import { Route as AdminWebApkRouteImport } from './routes/admin.web.apk'
import { Route as AdminViewUserIdRouteImport } from './routes/admin.view.$userId'
import { Route as ApiPublicVcardCodeRouteImport } from './routes/api.public.vcard.$code'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForVendorsRoute = ForVendorsRouteImport.update({
  id: '/for-vendors',
  path: '/for-vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCustomersRoute = ForCustomersRouteImport.update({
  id: '/for-customers',
  path: '/for-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorWalletRoute = VendorWalletRouteImport.update({
  id: '/vendor/wallet',
  path: '/vendor/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorStatusRoute = VendorStatusRouteImport.update({
  id: '/vendor/status',
  path: '/vendor/status',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSocialRoute = VendorSocialRouteImport.update({
  id: '/vendor/social',
  path: '/vendor/social',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorShopRoute = VendorShopRouteImport.update({
  id: '/vendor/shop',
  path: '/vendor/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorServicesRoute = VendorServicesRouteImport.update({
  id: '/vendor/services',
  path: '/vendor/services',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRegisterRoute = VendorRegisterRouteImport.update({
  id: '/vendor/register',
  path: '/vendor/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorKycRoute = VendorKycRouteImport.update({
  id: '/vendor/kyc',
  path: '/vendor/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorInstallRoute = VendorInstallRouteImport.update({
  id: '/vendor/install',
  path: '/vendor/install',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorChatRoute = VendorChatRouteImport.update({
  id: '/vendor/chat',
  path: '/vendor/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CCodeRoute = CCodeRouteImport.update({
  id: '/c/$code',
  path: '/c/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestAccountsRoute = AdminTestAccountsRouteImport.update({
  id: '/test-accounts',
  path: '/test-accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemStatusRoute = AdminSystemStatusRouteImport.update({
  id: '/system-status',
  path: '/system-status',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmsRoute = AdminSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapsRoute = AdminMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLookupRoute = AdminLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticsRoute = AdminLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycReviewRoute = AdminKycReviewRouteImport.update({
  id: '/kyc-review',
  path: '/kyc-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFirebaseRoute = AdminFirebaseRouteImport.update({
  id: '/firebase',
  path: '/firebase',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoinsRoute = AdminCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCashfreeRoute = AdminCashfreeRouteImport.update({
  id: '/cashfree',
  path: '/cashfree',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebIndexRoute = AdminWebIndexRouteImport.update({
  id: '/web/',
  path: '/web/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorLeadIdRoute = VendorLeadIdRouteImport.update({
  id: '/vendor/lead/$id',
  path: '/vendor/lead/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVendorLocationRoute = ApiPublicVendorLocationRouteImport.update({
  id: '/api/public/vendor-location',
  path: '/api/public/vendor-location',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebTestimonialsRoute = AdminWebTestimonialsRouteImport.update({
  id: '/web/testimonials',
  path: '/web/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebSeoRoute = AdminWebSeoRouteImport.update({
  id: '/web/seo',
  path: '/web/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebSectionsRoute = AdminWebSectionsRouteImport.update({
  id: '/web/sections',
  path: '/web/sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebPricingRoute = AdminWebPricingRouteImport.update({
  id: '/web/pricing',
  path: '/web/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebOffersRoute = AdminWebOffersRouteImport.update({
  id: '/web/offers',
  path: '/web/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebMediaRoute = AdminWebMediaRouteImport.update({
  id: '/web/media',
  path: '/web/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebHeroRoute = AdminWebHeroRouteImport.update({
  id: '/web/hero',
  path: '/web/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebFormsRoute = AdminWebFormsRouteImport.update({
  id: '/web/forms',
  path: '/web/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebFaqsRoute = AdminWebFaqsRouteImport.update({
  id: '/web/faqs',
  path: '/web/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebDevicesRoute = AdminWebDevicesRouteImport.update({
  id: '/web/devices',
  path: '/web/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebBlogRoute = AdminWebBlogRouteImport.update({
  id: '/web/blog',
  path: '/web/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebApkRoute = AdminWebApkRouteImport.update({
  id: '/web/apk',
  path: '/web/apk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminViewUserIdRoute = AdminViewUserIdRouteImport.update({
  id: '/view/$userId',
  path: '/view/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicVcardCodeRoute = ApiPublicVcardCodeRouteImport.update({
  id: '/api/public/vcard/$code',
  path: '/api/public/vcard/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/for-customers': typeof ForCustomersRoute
  '/for-vendors': typeof ForVendorsRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/quick': typeof QuickRoute
  '/referral': typeof ReferralRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/status': typeof StatusRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/vendors': typeof VendorsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/cashfree': typeof AdminCashfreeRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/firebase': typeof AdminFirebaseRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/kyc-review': typeof AdminKycReviewRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/lookup': typeof AdminLookupRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/system-status': typeof AdminSystemStatusRoute
  '/admin/test-accounts': typeof AdminTestAccountsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/c/$code': typeof CCodeRoute
  '/f/$slug': typeof FSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/r/$code': typeof RCodeRoute
  '/vendor/chat': typeof VendorChatRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/install': typeof VendorInstallRoute
  '/vendor/kyc': typeof VendorKycRoute
  '/vendor/register': typeof VendorRegisterRoute
  '/vendor/services': typeof VendorServicesRoute
  '/vendor/shop': typeof VendorShopRoute
  '/vendor/social': typeof VendorSocialRoute
  '/vendor/status': typeof VendorStatusRoute
  '/vendor/wallet': typeof VendorWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/view/$userId': typeof AdminViewUserIdRoute
  '/admin/web/apk': typeof AdminWebApkRoute
  '/admin/web/blog': typeof AdminWebBlogRoute
  '/admin/web/devices': typeof AdminWebDevicesRoute
  '/admin/web/faqs': typeof AdminWebFaqsRoute
  '/admin/web/forms': typeof AdminWebFormsRoute
  '/admin/web/hero': typeof AdminWebHeroRoute
  '/admin/web/media': typeof AdminWebMediaRoute
  '/admin/web/offers': typeof AdminWebOffersRoute
  '/admin/web/pricing': typeof AdminWebPricingRoute
  '/admin/web/sections': typeof AdminWebSectionsRoute
  '/admin/web/seo': typeof AdminWebSeoRoute
  '/admin/web/testimonials': typeof AdminWebTestimonialsRoute
  '/api/public/vendor-location': typeof ApiPublicVendorLocationRoute
  '/vendor/lead/$id': typeof VendorLeadIdRoute
  '/admin/web/': typeof AdminWebIndexRoute
  '/api/public/vcard/$code': typeof ApiPublicVcardCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/for-customers': typeof ForCustomersRoute
  '/for-vendors': typeof ForVendorsRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/quick': typeof QuickRoute
  '/referral': typeof ReferralRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/status': typeof StatusRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/vendors': typeof VendorsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/cashfree': typeof AdminCashfreeRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/firebase': typeof AdminFirebaseRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/kyc-review': typeof AdminKycReviewRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/lookup': typeof AdminLookupRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/system-status': typeof AdminSystemStatusRoute
  '/admin/test-accounts': typeof AdminTestAccountsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/c/$code': typeof CCodeRoute
  '/f/$slug': typeof FSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/r/$code': typeof RCodeRoute
  '/vendor/chat': typeof VendorChatRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/install': typeof VendorInstallRoute
  '/vendor/kyc': typeof VendorKycRoute
  '/vendor/register': typeof VendorRegisterRoute
  '/vendor/services': typeof VendorServicesRoute
  '/vendor/shop': typeof VendorShopRoute
  '/vendor/social': typeof VendorSocialRoute
  '/vendor/status': typeof VendorStatusRoute
  '/vendor/wallet': typeof VendorWalletRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/view/$userId': typeof AdminViewUserIdRoute
  '/admin/web/apk': typeof AdminWebApkRoute
  '/admin/web/blog': typeof AdminWebBlogRoute
  '/admin/web/devices': typeof AdminWebDevicesRoute
  '/admin/web/faqs': typeof AdminWebFaqsRoute
  '/admin/web/forms': typeof AdminWebFormsRoute
  '/admin/web/hero': typeof AdminWebHeroRoute
  '/admin/web/media': typeof AdminWebMediaRoute
  '/admin/web/offers': typeof AdminWebOffersRoute
  '/admin/web/pricing': typeof AdminWebPricingRoute
  '/admin/web/sections': typeof AdminWebSectionsRoute
  '/admin/web/seo': typeof AdminWebSeoRoute
  '/admin/web/testimonials': typeof AdminWebTestimonialsRoute
  '/api/public/vendor-location': typeof ApiPublicVendorLocationRoute
  '/vendor/lead/$id': typeof VendorLeadIdRoute
  '/admin/web': typeof AdminWebIndexRoute
  '/api/public/vcard/$code': typeof ApiPublicVcardCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/for-customers': typeof ForCustomersRoute
  '/for-vendors': typeof ForVendorsRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/quick': typeof QuickRoute
  '/referral': typeof ReferralRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/status': typeof StatusRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/vendors': typeof VendorsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/cashfree': typeof AdminCashfreeRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/firebase': typeof AdminFirebaseRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/kyc-review': typeof AdminKycReviewRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/lookup': typeof AdminLookupRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/system-status': typeof AdminSystemStatusRoute
  '/admin/test-accounts': typeof AdminTestAccountsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/c/$code': typeof CCodeRoute
  '/f/$slug': typeof FSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/r/$code': typeof RCodeRoute
  '/vendor/chat': typeof VendorChatRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/install': typeof VendorInstallRoute
  '/vendor/kyc': typeof VendorKycRoute
  '/vendor/register': typeof VendorRegisterRoute
  '/vendor/services': typeof VendorServicesRoute
  '/vendor/shop': typeof VendorShopRoute
  '/vendor/social': typeof VendorSocialRoute
  '/vendor/status': typeof VendorStatusRoute
  '/vendor/wallet': typeof VendorWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/view/$userId': typeof AdminViewUserIdRoute
  '/admin/web/apk': typeof AdminWebApkRoute
  '/admin/web/blog': typeof AdminWebBlogRoute
  '/admin/web/devices': typeof AdminWebDevicesRoute
  '/admin/web/faqs': typeof AdminWebFaqsRoute
  '/admin/web/forms': typeof AdminWebFormsRoute
  '/admin/web/hero': typeof AdminWebHeroRoute
  '/admin/web/media': typeof AdminWebMediaRoute
  '/admin/web/offers': typeof AdminWebOffersRoute
  '/admin/web/pricing': typeof AdminWebPricingRoute
  '/admin/web/sections': typeof AdminWebSectionsRoute
  '/admin/web/seo': typeof AdminWebSeoRoute
  '/admin/web/testimonials': typeof AdminWebTestimonialsRoute
  '/api/public/vendor-location': typeof ApiPublicVendorLocationRoute
  '/vendor/lead/$id': typeof VendorLeadIdRoute
  '/admin/web/': typeof AdminWebIndexRoute
  '/api/public/vcard/$code': typeof ApiPublicVcardCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/contact'
    | '/download'
    | '/features'
    | '/for-customers'
    | '/for-vendors'
    | '/home'
    | '/orders'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/quick'
    | '/referral'
    | '/refund-policy'
    | '/register'
    | '/services'
    | '/shipping-policy'
    | '/status'
    | '/terms-and-conditions'
    | '/vendors'
    | '/admin/branding'
    | '/admin/cashfree'
    | '/admin/catalog'
    | '/admin/coins'
    | '/admin/customers'
    | '/admin/devices'
    | '/admin/feedback'
    | '/admin/firebase'
    | '/admin/forms'
    | '/admin/kyc'
    | '/admin/kyc-review'
    | '/admin/legal'
    | '/admin/login'
    | '/admin/logistics'
    | '/admin/lookup'
    | '/admin/maps'
    | '/admin/notifications'
    | '/admin/onboarding'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/referrals'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/staff'
    | '/admin/system-status'
    | '/admin/test-accounts'
    | '/admin/vendors'
    | '/admin/whatsapp'
    | '/blog/$slug'
    | '/c/$code'
    | '/f/$slug'
    | '/product/$id'
    | '/r/$code'
    | '/vendor/chat'
    | '/vendor/dashboard'
    | '/vendor/install'
    | '/vendor/kyc'
    | '/vendor/register'
    | '/vendor/services'
    | '/vendor/shop'
    | '/vendor/social'
    | '/vendor/status'
    | '/vendor/wallet'
    | '/admin/'
    | '/blog/'
    | '/admin/view/$userId'
    | '/admin/web/apk'
    | '/admin/web/blog'
    | '/admin/web/devices'
    | '/admin/web/faqs'
    | '/admin/web/forms'
    | '/admin/web/hero'
    | '/admin/web/media'
    | '/admin/web/offers'
    | '/admin/web/pricing'
    | '/admin/web/sections'
    | '/admin/web/seo'
    | '/admin/web/testimonials'
    | '/api/public/vendor-location'
    | '/vendor/lead/$id'
    | '/admin/web/'
    | '/api/public/vcard/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/contact'
    | '/download'
    | '/features'
    | '/for-customers'
    | '/for-vendors'
    | '/home'
    | '/orders'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/quick'
    | '/referral'
    | '/refund-policy'
    | '/register'
    | '/services'
    | '/shipping-policy'
    | '/status'
    | '/terms-and-conditions'
    | '/vendors'
    | '/admin/branding'
    | '/admin/cashfree'
    | '/admin/catalog'
    | '/admin/coins'
    | '/admin/customers'
    | '/admin/devices'
    | '/admin/feedback'
    | '/admin/firebase'
    | '/admin/forms'
    | '/admin/kyc'
    | '/admin/kyc-review'
    | '/admin/legal'
    | '/admin/login'
    | '/admin/logistics'
    | '/admin/lookup'
    | '/admin/maps'
    | '/admin/notifications'
    | '/admin/onboarding'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/referrals'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/staff'
    | '/admin/system-status'
    | '/admin/test-accounts'
    | '/admin/vendors'
    | '/admin/whatsapp'
    | '/blog/$slug'
    | '/c/$code'
    | '/f/$slug'
    | '/product/$id'
    | '/r/$code'
    | '/vendor/chat'
    | '/vendor/dashboard'
    | '/vendor/install'
    | '/vendor/kyc'
    | '/vendor/register'
    | '/vendor/services'
    | '/vendor/shop'
    | '/vendor/social'
    | '/vendor/status'
    | '/vendor/wallet'
    | '/admin'
    | '/blog'
    | '/admin/view/$userId'
    | '/admin/web/apk'
    | '/admin/web/blog'
    | '/admin/web/devices'
    | '/admin/web/faqs'
    | '/admin/web/forms'
    | '/admin/web/hero'
    | '/admin/web/media'
    | '/admin/web/offers'
    | '/admin/web/pricing'
    | '/admin/web/sections'
    | '/admin/web/seo'
    | '/admin/web/testimonials'
    | '/api/public/vendor-location'
    | '/vendor/lead/$id'
    | '/admin/web'
    | '/api/public/vcard/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/contact'
    | '/download'
    | '/features'
    | '/for-customers'
    | '/for-vendors'
    | '/home'
    | '/orders'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/quick'
    | '/referral'
    | '/refund-policy'
    | '/register'
    | '/services'
    | '/shipping-policy'
    | '/status'
    | '/terms-and-conditions'
    | '/vendors'
    | '/admin/branding'
    | '/admin/cashfree'
    | '/admin/catalog'
    | '/admin/coins'
    | '/admin/customers'
    | '/admin/devices'
    | '/admin/feedback'
    | '/admin/firebase'
    | '/admin/forms'
    | '/admin/kyc'
    | '/admin/kyc-review'
    | '/admin/legal'
    | '/admin/login'
    | '/admin/logistics'
    | '/admin/lookup'
    | '/admin/maps'
    | '/admin/notifications'
    | '/admin/onboarding'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/referrals'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/staff'
    | '/admin/system-status'
    | '/admin/test-accounts'
    | '/admin/vendors'
    | '/admin/whatsapp'
    | '/blog/$slug'
    | '/c/$code'
    | '/f/$slug'
    | '/product/$id'
    | '/r/$code'
    | '/vendor/chat'
    | '/vendor/dashboard'
    | '/vendor/install'
    | '/vendor/kyc'
    | '/vendor/register'
    | '/vendor/services'
    | '/vendor/shop'
    | '/vendor/social'
    | '/vendor/status'
    | '/vendor/wallet'
    | '/admin/'
    | '/blog/'
    | '/admin/view/$userId'
    | '/admin/web/apk'
    | '/admin/web/blog'
    | '/admin/web/devices'
    | '/admin/web/faqs'
    | '/admin/web/forms'
    | '/admin/web/hero'
    | '/admin/web/media'
    | '/admin/web/offers'
    | '/admin/web/pricing'
    | '/admin/web/sections'
    | '/admin/web/seo'
    | '/admin/web/testimonials'
    | '/api/public/vendor-location'
    | '/vendor/lead/$id'
    | '/admin/web/'
    | '/api/public/vcard/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  FeaturesRoute: typeof FeaturesRoute
  ForCustomersRoute: typeof ForCustomersRoute
  ForVendorsRoute: typeof ForVendorsRoute
  HomeRoute: typeof HomeRoute
  OrdersRoute: typeof OrdersRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  QuickRoute: typeof QuickRoute
  ReferralRoute: typeof ReferralRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  StatusRoute: typeof StatusRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  VendorsRoute: typeof VendorsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CCodeRoute: typeof CCodeRoute
  FSlugRoute: typeof FSlugRoute
  ProductIdRoute: typeof ProductIdRoute
  RCodeRoute: typeof RCodeRoute
  VendorChatRoute: typeof VendorChatRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorInstallRoute: typeof VendorInstallRoute
  VendorKycRoute: typeof VendorKycRoute
  VendorRegisterRoute: typeof VendorRegisterRoute
  VendorServicesRoute: typeof VendorServicesRoute
  VendorShopRoute: typeof VendorShopRoute
  VendorSocialRoute: typeof VendorSocialRoute
  VendorStatusRoute: typeof VendorStatusRoute
  VendorWalletRoute: typeof VendorWalletRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicVendorLocationRoute: typeof ApiPublicVendorLocationRoute
  VendorLeadIdRoute: typeof VendorLeadIdRoute
  ApiPublicVcardCodeRoute: typeof ApiPublicVcardCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-vendors': {
      id: '/for-vendors'
      path: '/for-vendors'
      fullPath: '/for-vendors'
      preLoaderRoute: typeof ForVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-customers': {
      id: '/for-customers'
      path: '/for-customers'
      fullPath: '/for-customers'
      preLoaderRoute: typeof ForCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/wallet': {
      id: '/vendor/wallet'
      path: '/vendor/wallet'
      fullPath: '/vendor/wallet'
      preLoaderRoute: typeof VendorWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/status': {
      id: '/vendor/status'
      path: '/vendor/status'
      fullPath: '/vendor/status'
      preLoaderRoute: typeof VendorStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/social': {
      id: '/vendor/social'
      path: '/vendor/social'
      fullPath: '/vendor/social'
      preLoaderRoute: typeof VendorSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/shop': {
      id: '/vendor/shop'
      path: '/vendor/shop'
      fullPath: '/vendor/shop'
      preLoaderRoute: typeof VendorShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/services': {
      id: '/vendor/services'
      path: '/vendor/services'
      fullPath: '/vendor/services'
      preLoaderRoute: typeof VendorServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/register': {
      id: '/vendor/register'
      path: '/vendor/register'
      fullPath: '/vendor/register'
      preLoaderRoute: typeof VendorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/kyc': {
      id: '/vendor/kyc'
      path: '/vendor/kyc'
      fullPath: '/vendor/kyc'
      preLoaderRoute: typeof VendorKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/install': {
      id: '/vendor/install'
      path: '/vendor/install'
      fullPath: '/vendor/install'
      preLoaderRoute: typeof VendorInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/chat': {
      id: '/vendor/chat'
      path: '/vendor/chat'
      fullPath: '/vendor/chat'
      preLoaderRoute: typeof VendorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$code': {
      id: '/c/$code'
      path: '/c/$code'
      fullPath: '/c/$code'
      preLoaderRoute: typeof CCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/test-accounts': {
      id: '/admin/test-accounts'
      path: '/test-accounts'
      fullPath: '/admin/test-accounts'
      preLoaderRoute: typeof AdminTestAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-status': {
      id: '/admin/system-status'
      path: '/system-status'
      fullPath: '/admin/system-status'
      preLoaderRoute: typeof AdminSystemStatusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sms': {
      id: '/admin/sms'
      path: '/sms'
      fullPath: '/admin/sms'
      preLoaderRoute: typeof AdminSmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maps': {
      id: '/admin/maps'
      path: '/maps'
      fullPath: '/admin/maps'
      preLoaderRoute: typeof AdminMapsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lookup': {
      id: '/admin/lookup'
      path: '/lookup'
      fullPath: '/admin/lookup'
      preLoaderRoute: typeof AdminLookupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistics': {
      id: '/admin/logistics'
      path: '/logistics'
      fullPath: '/admin/logistics'
      preLoaderRoute: typeof AdminLogisticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc-review': {
      id: '/admin/kyc-review'
      path: '/kyc-review'
      fullPath: '/admin/kyc-review'
      preLoaderRoute: typeof AdminKycReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/firebase': {
      id: '/admin/firebase'
      path: '/firebase'
      fullPath: '/admin/firebase'
      preLoaderRoute: typeof AdminFirebaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devices': {
      id: '/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coins': {
      id: '/admin/coins'
      path: '/coins'
      fullPath: '/admin/coins'
      preLoaderRoute: typeof AdminCoinsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cashfree': {
      id: '/admin/cashfree'
      path: '/cashfree'
      fullPath: '/admin/cashfree'
      preLoaderRoute: typeof AdminCashfreeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/web/': {
      id: '/admin/web/'
      path: '/web'
      fullPath: '/admin/web/'
      preLoaderRoute: typeof AdminWebIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/lead/$id': {
      id: '/vendor/lead/$id'
      path: '/vendor/lead/$id'
      fullPath: '/vendor/lead/$id'
      preLoaderRoute: typeof VendorLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vendor-location': {
      id: '/api/public/vendor-location'
      path: '/api/public/vendor-location'
      fullPath: '/api/public/vendor-location'
      preLoaderRoute: typeof ApiPublicVendorLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/web/testimonials': {
      id: '/admin/web/testimonials'
      path: '/web/testimonials'
      fullPath: '/admin/web/testimonials'
      preLoaderRoute: typeof AdminWebTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/web/seo': {
      id: '/admin/web/seo'
      path: '/web/seo'
      fullPath: '/admin/web/seo'
      preLoaderRoute: typeof AdminWebSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/web/sections': {
      id: '/admin/web/sections'
      path: '/web/sections'
      fullPath: '/admin/web/sections'
      preLoaderRoute: typeof AdminWebSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/web/pricing': {
      id: '/admin/web/pricing'
      path: '/web/pricing'
      fullPath: '/admin/web/pricing'
      preLoaderRoute: typeof AdminWebPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/web/offers': {
      id: '/admin/web/offers'
      path: '/web/offers'
      fullPath: '/admin/web/offers'
      preLoaderRoute: typeof AdminWebOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/web/media': {
      id: '/admin/web/media'
      path: '/web/media'
      fullPath: '/admin/web/media'
      preLoaderRoute: typeof AdminWebMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/web/hero': {
      id: '/admin/web/hero'
      path: '/web/hero'
      fullPath: '/admin/web/hero'
      preLoaderRoute: typeof AdminWebHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/web/forms': {
      id: '/admin/web/forms'
      path: '/web/forms'
      fullPath: '/admin/web/forms'
      preLoaderRoute: typeof AdminWebFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/web/faqs': {
      id: '/admin/web/faqs'
      path: '/web/faqs'
      fullPath: '/admin/web/faqs'
      preLoaderRoute: typeof AdminWebFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/web/devices': {
      id: '/admin/web/devices'
      path: '/web/devices'
      fullPath: '/admin/web/devices'
      preLoaderRoute: typeof AdminWebDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/web/blog': {
      id: '/admin/web/blog'
      path: '/web/blog'
      fullPath: '/admin/web/blog'
      preLoaderRoute: typeof AdminWebBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/web/apk': {
      id: '/admin/web/apk'
      path: '/web/apk'
      fullPath: '/admin/web/apk'
      preLoaderRoute: typeof AdminWebApkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/view/$userId': {
      id: '/admin/view/$userId'
      path: '/view/$userId'
      fullPath: '/admin/view/$userId'
      preLoaderRoute: typeof AdminViewUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/vcard/$code': {
      id: '/api/public/vcard/$code'
      path: '/api/public/vcard/$code'
      fullPath: '/api/public/vcard/$code'
      preLoaderRoute: typeof ApiPublicVcardCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminCashfreeRoute: typeof AdminCashfreeRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCoinsRoute: typeof AdminCoinsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDevicesRoute: typeof AdminDevicesRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminFirebaseRoute: typeof AdminFirebaseRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminKycReviewRoute: typeof AdminKycReviewRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogisticsRoute: typeof AdminLogisticsRoute
  AdminLookupRoute: typeof AdminLookupRoute
  AdminMapsRoute: typeof AdminMapsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSmsRoute: typeof AdminSmsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminSystemStatusRoute: typeof AdminSystemStatusRoute
  AdminTestAccountsRoute: typeof AdminTestAccountsRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminViewUserIdRoute: typeof AdminViewUserIdRoute
  AdminWebApkRoute: typeof AdminWebApkRoute
  AdminWebBlogRoute: typeof AdminWebBlogRoute
  AdminWebDevicesRoute: typeof AdminWebDevicesRoute
  AdminWebFaqsRoute: typeof AdminWebFaqsRoute
  AdminWebFormsRoute: typeof AdminWebFormsRoute
  AdminWebHeroRoute: typeof AdminWebHeroRoute
  AdminWebMediaRoute: typeof AdminWebMediaRoute
  AdminWebOffersRoute: typeof AdminWebOffersRoute
  AdminWebPricingRoute: typeof AdminWebPricingRoute
  AdminWebSectionsRoute: typeof AdminWebSectionsRoute
  AdminWebSeoRoute: typeof AdminWebSeoRoute
  AdminWebTestimonialsRoute: typeof AdminWebTestimonialsRoute
  AdminWebIndexRoute: typeof AdminWebIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrandingRoute: AdminBrandingRoute,
  AdminCashfreeRoute: AdminCashfreeRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCoinsRoute: AdminCoinsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDevicesRoute: AdminDevicesRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminFirebaseRoute: AdminFirebaseRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminKycRoute: AdminKycRoute,
  AdminKycReviewRoute: AdminKycReviewRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogisticsRoute: AdminLogisticsRoute,
  AdminLookupRoute: AdminLookupRoute,
  AdminMapsRoute: AdminMapsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSmsRoute: AdminSmsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminSystemStatusRoute: AdminSystemStatusRoute,
  AdminTestAccountsRoute: AdminTestAccountsRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminViewUserIdRoute: AdminViewUserIdRoute,
  AdminWebApkRoute: AdminWebApkRoute,
  AdminWebBlogRoute: AdminWebBlogRoute,
  AdminWebDevicesRoute: AdminWebDevicesRoute,
  AdminWebFaqsRoute: AdminWebFaqsRoute,
  AdminWebFormsRoute: AdminWebFormsRoute,
  AdminWebHeroRoute: AdminWebHeroRoute,
  AdminWebMediaRoute: AdminWebMediaRoute,
  AdminWebOffersRoute: AdminWebOffersRoute,
  AdminWebPricingRoute: AdminWebPricingRoute,
  AdminWebSectionsRoute: AdminWebSectionsRoute,
  AdminWebSeoRoute: AdminWebSeoRoute,
  AdminWebTestimonialsRoute: AdminWebTestimonialsRoute,
  AdminWebIndexRoute: AdminWebIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  FeaturesRoute: FeaturesRoute,
  ForCustomersRoute: ForCustomersRoute,
  ForVendorsRoute: ForVendorsRoute,
  HomeRoute: HomeRoute,
  OrdersRoute: OrdersRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  QuickRoute: QuickRoute,
  ReferralRoute: ReferralRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  StatusRoute: StatusRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  VendorsRoute: VendorsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CCodeRoute: CCodeRoute,
  FSlugRoute: FSlugRoute,
  ProductIdRoute: ProductIdRoute,
  RCodeRoute: RCodeRoute,
  VendorChatRoute: VendorChatRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorInstallRoute: VendorInstallRoute,
  VendorKycRoute: VendorKycRoute,
  VendorRegisterRoute: VendorRegisterRoute,
  VendorServicesRoute: VendorServicesRoute,
  VendorShopRoute: VendorShopRoute,
  VendorSocialRoute: VendorSocialRoute,
  VendorStatusRoute: VendorStatusRoute,
  VendorWalletRoute: VendorWalletRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicVendorLocationRoute: ApiPublicVendorLocationRoute,
  VendorLeadIdRoute: VendorLeadIdRoute,
  ApiPublicVcardCodeRoute: ApiPublicVcardCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
