/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorShopRouteImport } from './routes/vendor.shop'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as VendorLeadIdRouteImport } from './routes/vendor.lead.$id'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorShopRoute = VendorShopRouteImport.update({
  id: '/vendor/shop',
  path: '/vendor/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLeadIdRoute = VendorLeadIdRouteImport.update({
  id: '/vendor/lead/$id',
  path: '/vendor/lead/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/quick': typeof QuickRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/status': typeof StatusRoute
  '/vendors': typeof VendorsRoute
  '/product/$id': typeof ProductIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/shop': typeof VendorShopRoute
  '/vendor/lead/$id': typeof VendorLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/quick': typeof QuickRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/status': typeof StatusRoute
  '/vendors': typeof VendorsRoute
  '/product/$id': typeof ProductIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/shop': typeof VendorShopRoute
  '/vendor/lead/$id': typeof VendorLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/quick': typeof QuickRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/status': typeof StatusRoute
  '/vendors': typeof VendorsRoute
  '/product/$id': typeof ProductIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/shop': typeof VendorShopRoute
  '/vendor/lead/$id': typeof VendorLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/home'
    | '/orders'
    | '/profile'
    | '/quick'
    | '/register'
    | '/services'
    | '/status'
    | '/vendors'
    | '/product/$id'
    | '/vendor/dashboard'
    | '/vendor/shop'
    | '/vendor/lead/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/home'
    | '/orders'
    | '/profile'
    | '/quick'
    | '/register'
    | '/services'
    | '/status'
    | '/vendors'
    | '/product/$id'
    | '/vendor/dashboard'
    | '/vendor/shop'
    | '/vendor/lead/$id'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/home'
    | '/orders'
    | '/profile'
    | '/quick'
    | '/register'
    | '/services'
    | '/status'
    | '/vendors'
    | '/product/$id'
    | '/vendor/dashboard'
    | '/vendor/shop'
    | '/vendor/lead/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  HomeRoute: typeof HomeRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  QuickRoute: typeof QuickRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  StatusRoute: typeof StatusRoute
  VendorsRoute: typeof VendorsRoute
  ProductIdRoute: typeof ProductIdRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorShopRoute: typeof VendorShopRoute
  VendorLeadIdRoute: typeof VendorLeadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/shop': {
      id: '/vendor/shop'
      path: '/vendor/shop'
      fullPath: '/vendor/shop'
      preLoaderRoute: typeof VendorShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/lead/$id': {
      id: '/vendor/lead/$id'
      path: '/vendor/lead/$id'
      fullPath: '/vendor/lead/$id'
      preLoaderRoute: typeof VendorLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  HomeRoute: HomeRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  QuickRoute: QuickRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  StatusRoute: StatusRoute,
  VendorsRoute: VendorsRoute,
  ProductIdRoute: ProductIdRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorShopRoute: VendorShopRoute,
  VendorLeadIdRoute: VendorLeadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
